# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simon Müller
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

email: ""
twitter_username: ""
github_username:  ""
repository: ""

nav_links: [
  {'title': 'Home', 'url': '/'},
  {'title': 'Quotes', 'url': '/quotes/'},
  {'title': 'Notes', 'url': '/notes/'},
  {'title': 'About', 'url': '/about/'}
]

google_analytics: UA-120258429-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
# Minimize CSS and strip comments
# sass:
#     style: compressed
